// A feed post. Pure Dart (Domain) — manual equality, no serialization.
//
// Mirrors the deployed `posts` table (migration 0510 + 0511). Author display
// fields (name/username/photo) come from an embedded `profiles` join at the
// data layer so the feed can render the author without a second query.
import 'post_media.dart';

/// Wrapped post id (never a raw String — CLAUDE.md §5.1).
class PostId {
  const PostId(this.value);
  final String value;
  @override
  bool operator ==(Object other) => other is PostId && other.value == value;
  @override
  int get hashCode => value.hashCode;
  @override
  String toString() => value;
}

/// Whose voice the post speaks in (§6.5). MVP composes `personal` only.
enum PostAuthorContext {
  personal,
  teamManager,
  tournamentOrganizer;

  static PostAuthorContext fromWire(String? s) => switch (s) {
        'team_manager' => PostAuthorContext.teamManager,
        'tournament_organizer' => PostAuthorContext.tournamentOrganizer,
        _ => PostAuthorContext.personal,
      };

  String get wire => switch (this) {
        PostAuthorContext.personal => 'personal',
        PostAuthorContext.teamManager => 'team_manager',
        PostAuthorContext.tournamentOrganizer => 'tournament_organizer',
      };
}

/// MVP post types (auto types ship in v1.1).
enum PostType {
  text,
  photo,
  matchAnnouncement,
  recruitment,
  tournamentUpdate;

  static PostType fromWire(String? s) => switch (s) {
        'photo' => PostType.photo,
        'match_announcement' => PostType.matchAnnouncement,
        'recruitment' => PostType.recruitment,
        'tournament_update' => PostType.tournamentUpdate,
        _ => PostType.text,
      };

  String get wire => switch (this) {
        PostType.text => 'text',
        PostType.photo => 'photo',
        PostType.matchAnnouncement => 'match_announcement',
        PostType.recruitment => 'recruitment',
        PostType.tournamentUpdate => 'tournament_update',
      };
}

enum PostStatus {
  active,
  hidden,
  deleted,
  reported;

  static PostStatus fromWire(String? s) => switch (s) {
        'hidden' => PostStatus.hidden,
        'deleted' => PostStatus.deleted,
        'reported' => PostStatus.reported,
        _ => PostStatus.active,
      };
}

class Post {
  const Post({
    required this.id,
    required this.authorId,
    required this.authorContext,
    this.contextEntityId,
    required this.type,
    this.text,
    this.media = const [],
    this.linkedMatchId,
    this.linkedTournamentId,
    this.linkedTeamId,
    this.linkedPlayerIds = const [],
    this.autoGenerated = false,
    this.isPinned = false,
    this.likesCount = 0,
    this.commentsCount = 0,
    this.sharesCount = 0,
    this.status = PostStatus.active,
    required this.createdAt,
    this.editedAt,
    required this.updatedAt,
    // Author display (from embedded profiles join).
    this.authorName,
    this.authorUsername,
    this.authorPhotoUrl,
  });

  final PostId id;
  final String authorId;
  final PostAuthorContext authorContext;
  final String? contextEntityId;
  final PostType type;
  final String? text;
  final List<PostMedia> media;
  final String? linkedMatchId;
  final String? linkedTournamentId;
  final String? linkedTeamId;
  final List<String> linkedPlayerIds;
  final bool autoGenerated;
  final bool isPinned;
  final int likesCount;
  final int commentsCount;
  final int sharesCount;
  final PostStatus status;
  final DateTime createdAt;
  final DateTime? editedAt;
  final DateTime updatedAt;

  final String? authorName;
  final String? authorUsername;
  final String? authorPhotoUrl;

  bool get hasMedia => media.isNotEmpty;

  /// Two-letter monogram for the avatar/crest, derived from the author name.
  String get authorMonogram {
    final n = (authorName ?? '').trim();
    if (n.isEmpty) return '?';
    final parts = n.split(RegExp(r'\s+'));
    if (parts.length == 1) {
      return parts.first.substring(0, parts.first.length >= 2 ? 2 : 1).toUpperCase();
    }
    return (parts.first[0] + parts[1][0]).toUpperCase();
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Post &&
          other.id == id &&
          other.text == text &&
          other.status == status &&
          other.likesCount == likesCount &&
          other.commentsCount == commentsCount &&
          other.isPinned == isPinned &&
          other.updatedAt == updatedAt &&
          _sameMedia(other.media);

  bool _sameMedia(List<PostMedia> o) {
    if (o.length != media.length) return false;
    for (var i = 0; i < o.length; i++) {
      if (o[i] != media[i]) return false;
    }
    return true;
  }

  @override
  int get hashCode => Object.hash(id, text, status, likesCount, commentsCount,
      isPinned, updatedAt, media.length);
}
