// A feed post. Pure Dart (Domain) — manual equality, no serialization.
//
// Mirrors the deployed `posts` table (migration 0510 + 0511). Author display
// fields (name/username/photo) come from an embedded `profiles` join at the
// data layer so the feed can render the author without a second query.
import 'package:freezed_annotation/freezed_annotation.dart';

import 'post_media.dart';

part 'post.freezed.dart';

/// Wrapped post id (never a raw String — CLAUDE.md §5.1).
class PostId {
  const PostId(this.value);
  final String value;
  @override
  bool operator ==(Object other) => other is PostId && other.value == value;
  @override
  int get hashCode => value.hashCode;
  @override
  String toString() => value;
}

/// Whose voice the post speaks in (§6.5). MVP composes `personal` only.
enum PostAuthorContext {
  personal,
  teamManager,
  tournamentOrganizer;

  static PostAuthorContext fromWire(String? s) => switch (s) {
        'team_manager' => PostAuthorContext.teamManager,
        'tournament_organizer' => PostAuthorContext.tournamentOrganizer,
        _ => PostAuthorContext.personal,
      };

  String get wire => switch (this) {
        PostAuthorContext.personal => 'personal',
        PostAuthorContext.teamManager => 'team_manager',
        PostAuthorContext.tournamentOrganizer => 'tournament_organizer',
      };
}

/// MVP post types (auto types ship in v1.1).
enum PostType {
  text,
  photo,
  matchAnnouncement,
  recruitment,
  tournamentUpdate;

  static PostType fromWire(String? s) => switch (s) {
        'photo' => PostType.photo,
        'match_announcement' => PostType.matchAnnouncement,
        'recruitment' => PostType.recruitment,
        'tournament_update' => PostType.tournamentUpdate,
        _ => PostType.text,
      };

  String get wire => switch (this) {
        PostType.text => 'text',
        PostType.photo => 'photo',
        PostType.matchAnnouncement => 'match_announcement',
        PostType.recruitment => 'recruitment',
        PostType.tournamentUpdate => 'tournament_update',
      };
}

enum PostStatus {
  active,
  hidden,
  deleted,
  reported;

  static PostStatus fromWire(String? s) => switch (s) {
        'hidden' => PostStatus.hidden,
        'deleted' => PostStatus.deleted,
        'reported' => PostStatus.reported,
        _ => PostStatus.active,
      };
}

@freezed
abstract class Post with _$Post {
  const factory Post({
    required PostId id,
    required String authorId,
    required PostAuthorContext authorContext,
    String? contextEntityId,
    required PostType type,
    String? text,
    @Default([]) List<PostMedia> media,
    String? linkedMatchId,
    String? linkedTournamentId,
    String? linkedTeamId,
    @Default([]) List<String> linkedPlayerIds,
    @Default(false) bool autoGenerated,
    @Default(false) bool isPinned,
    @Default(0) int likesCount,
    @Default(0) int commentsCount,
    @Default(0) int sharesCount,
    @Default(PostStatus.active) PostStatus status,
    required DateTime createdAt,
    DateTime? editedAt,
    required DateTime updatedAt,
    // Author display (from embedded profiles join).
    String? authorName,
    String? authorUsername,
    String? authorPhotoUrl,
  }) = _Post;

  const Post._();

  bool get hasMedia => media.isNotEmpty;

  /// Two-letter monogram for the avatar/crest, derived from the author name.
  String get authorMonogram {
    final n = (authorName ?? '').trim();
    if (n.isEmpty) return '?';
    final parts = n.split(RegExp(r'\s+'));
    if (parts.length == 1) {
      return parts.first.substring(0, parts.first.length >= 2 ? 2 : 1).toUpperCase();
    }
    return (parts.first[0] + parts[1][0]).toUpperCase();
  }
}
