import 'package:equatable/equatable.dart';

import 'post_media.dart';

/// Wrapped post id (never a raw String).
class PostId extends Equatable {
  const PostId(this.value);
  final String value;

  @override
  List<Object?> get props => [value];

  @override
  String toString() => value;
}

enum PostPublisherType {
  user,
  team,
  tournament,
  club,
}

enum PostKind {
  standard,
  recruitment,
  matchAnnouncement,
  matchResult,
  tournamentUpdate,
  rosterUpdate,
  milestone,
}

enum PostStatus {
  publishing,
  active,
  hidden,
  reported,
  deleted,
}

enum PostVisibility {
  public,
  followersOnly,
  private,
}

enum PostAuthorContext {
  personal,
  teamManager,
  tournamentAdmin,
  scorer,
}

class PostPublisher extends Equatable {
  const PostPublisher({
    required this.id,
    required this.type,
    required this.displayName,
    this.username,
    this.photoUrl,
  });

  final String id;
  final PostPublisherType type;
  final String displayName;
  final String? username;
  final String? photoUrl;

  @override
  List<Object?> get props => [id, type, displayName, username, photoUrl];
}

class PostCounts extends Equatable {
  const PostCounts({
    this.likes = 0,
    this.comments = 0,
    this.shares = 0,
  });

  final int likes;
  final int comments;
  final int shares;

  PostCounts copyWith({int? likes, int? comments, int? shares}) => PostCounts(
        likes: likes ?? this.likes,
        comments: comments ?? this.comments,
        shares: shares ?? this.shares,
      );

  @override
  List<Object?> get props => [likes, comments, shares];
}

class PostViewerInteractions extends Equatable {
  const PostViewerInteractions({
    this.isLiked = false,
    this.isBookmarked = false,
    this.isFollowingPublisher = false,
  });

  final bool isLiked;
  final bool isBookmarked;
  final bool isFollowingPublisher;

  PostViewerInteractions copyWith({
    bool? isLiked,
    bool? isBookmarked,
    bool? isFollowingPublisher,
  }) =>
      PostViewerInteractions(
        isLiked: isLiked ?? this.isLiked,
        isBookmarked: isBookmarked ?? this.isBookmarked,
        isFollowingPublisher:
            isFollowingPublisher ?? this.isFollowingPublisher,
      );

  @override
  List<Object?> get props => [isLiked, isBookmarked, isFollowingPublisher];
}

/// A feed post. Pure Dart (Domain) — Equatable, zero framework or wire knowledge.
class Post extends Equatable {
  const Post({
    required this.id,
    required this.createdByUserId,
    required this.publisher,
    required this.kind,
    this.text,
    this.visibility = PostVisibility.public,
    this.status = PostStatus.active,
    this.expectedMediaCount = 0,
    this.media = const [],
    this.counts = const PostCounts(),
    this.viewer = const PostViewerInteractions(),
    this.publishedAt,
    required this.createdAt,
    this.linkedMatchId,
    this.linkedTournamentId,
    this.linkedTeamId,
  });

  final PostId id;
  final String createdByUserId;
  final PostPublisher publisher;
  final PostKind kind;
  final String? text;
  final PostVisibility visibility;
  final PostStatus status;
  final int expectedMediaCount;
  final List<PostMedia> media;
  final PostCounts counts;
  final PostViewerInteractions viewer;
  final DateTime? publishedAt;
  final DateTime createdAt;
  final String? linkedMatchId;
  final String? linkedTournamentId;
  final String? linkedTeamId;

  bool get hasPhotos => media.isNotEmpty;
  bool get hasMedia => media.isNotEmpty;
  bool get isPublishing => status == PostStatus.publishing;
  bool get isActive => status == PostStatus.active;

  // Convenience getters for UI components
  String get authorId => createdByUserId;
  String get displayName => publisher.displayName;
  String? get displayPhotoUrl => publisher.photoUrl;
  String? get displayUsername => publisher.username;
  String get displayMonogram =>
      displayName.isNotEmpty ? displayName[0].toUpperCase() : '';
  int get likesCount => counts.likes;
  int get commentsCount => counts.comments;
  int get sharesCount => counts.shares;
  bool get isLiked => viewer.isLiked;
  bool get isBookmarked => viewer.isBookmarked;
  bool get isFollowing => viewer.isFollowingPublisher;

  bool get isTeamPublisher => publisher.type == PostPublisherType.team;
  bool get isTournamentPublisher =>
      publisher.type == PostPublisherType.tournament;

  PostAuthorContext get authorContext => switch (publisher.type) {
        PostPublisherType.team => PostAuthorContext.teamManager,
        PostPublisherType.tournament => PostAuthorContext.tournamentAdmin,
        _ => PostAuthorContext.personal,
      };

  String? get contextEntityId => linkedTeamId ?? linkedTournamentId;
  String? get authorUsername => publisher.username;
  String get authorName => publisher.displayName;
  String get authorMonogram => displayMonogram;
  bool get autoGenerated => false;

  Post copyWith({
    PostId? id,
    String? createdByUserId,
    PostPublisher? publisher,
    PostKind? kind,
    String? Function()? text,
    PostVisibility? visibility,
    PostStatus? status,
    int? expectedMediaCount,
    List<PostMedia>? media,
    PostCounts? counts,
    PostViewerInteractions? viewer,
    DateTime? Function()? publishedAt,
    DateTime? createdAt,
    String? Function()? linkedMatchId,
    String? Function()? linkedTournamentId,
    String? Function()? linkedTeamId,
    bool? isLiked,
    int? likesCount,
    bool? isBookmarked,
    int? commentsCount,
  }) =>
      Post(
        id: id ?? this.id,
        createdByUserId: createdByUserId ?? this.createdByUserId,
        publisher: publisher ?? this.publisher,
        kind: kind ?? this.kind,
        text: text != null ? text() : this.text,
        visibility: visibility ?? this.visibility,
        status: status ?? this.status,
        expectedMediaCount: expectedMediaCount ?? this.expectedMediaCount,
        media: media ?? this.media,
        counts: (likesCount != null || commentsCount != null)
            ? (counts ?? this.counts).copyWith(
                likes: likesCount ?? this.counts.likes,
                comments: commentsCount ?? this.counts.comments,
              )
            : (counts ?? this.counts),
        viewer: (isLiked != null || isBookmarked != null)
            ? (viewer ?? this.viewer).copyWith(
                isLiked: isLiked ?? this.viewer.isLiked,
                isBookmarked: isBookmarked ?? this.viewer.isBookmarked,
              )
            : (viewer ?? this.viewer),
        publishedAt: publishedAt != null ? publishedAt() : this.publishedAt,
        createdAt: createdAt ?? this.createdAt,
        linkedMatchId:
            linkedMatchId != null ? linkedMatchId() : this.linkedMatchId,
        linkedTournamentId: linkedTournamentId != null
            ? linkedTournamentId()
            : this.linkedTournamentId,
        linkedTeamId:
            linkedTeamId != null ? linkedTeamId() : this.linkedTeamId,
      );

  @override
  List<Object?> get props => [
        id,
        createdByUserId,
        publisher,
        kind,
        text,
        visibility,
        status,
        expectedMediaCount,
        media,
        counts,
        viewer,
        publishedAt,
        createdAt,
        linkedMatchId,
        linkedTournamentId,
        linkedTeamId,
      ];
}
