// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'post_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_PostDto _$PostDtoFromJson(Map<String, dynamic> json) => _PostDto(
  postId: json['post_id'] as String,
  authorId: json['author_id'] as String,
  authorContext: json['author_context'] as String? ?? 'personal',
  contextEntityId: json['context_entity_id'] as String?,
  postType: json['post_type'] as String,
  text: json['text'] as String?,
  mediaUrls:
      (json['media_urls'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList() ??
      const <String>[],
  media: json['media'] as List<dynamic>? ?? const <dynamic>[],
  linkedMatchId: json['linked_match_id'] as String?,
  linkedTournamentId: json['linked_tournament_id'] as String?,
  linkedTeamId: json['linked_team_id'] as String?,
  linkedPlayerIds:
      (json['linked_player_ids'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList() ??
      const <String>[],
  autoGenerated: json['auto_generated'] as bool? ?? false,
  isPinned: json['is_pinned'] as bool? ?? false,
  likesCount: (json['likes_count'] as num?)?.toInt() ?? 0,
  commentsCount: (json['comments_count'] as num?)?.toInt() ?? 0,
  sharesCount: (json['shares_count'] as num?)?.toInt() ?? 0,
  status: json['status'] as String? ?? 'active',
  createdAt: json['created_at'] as String,
  editedAt: json['edited_at'] as String?,
  updatedAt: json['updated_at'] as String,
  author: json['author'] as Map<String, dynamic>?,
);

Map<String, dynamic> _$PostDtoToJson(_PostDto instance) => <String, dynamic>{
  'post_id': instance.postId,
  'author_id': instance.authorId,
  'author_context': instance.authorContext,
  'context_entity_id': instance.contextEntityId,
  'post_type': instance.postType,
  'text': instance.text,
  'media_urls': instance.mediaUrls,
  'media': instance.media,
  'linked_match_id': instance.linkedMatchId,
  'linked_tournament_id': instance.linkedTournamentId,
  'linked_team_id': instance.linkedTeamId,
  'linked_player_ids': instance.linkedPlayerIds,
  'auto_generated': instance.autoGenerated,
  'is_pinned': instance.isPinned,
  'likes_count': instance.likesCount,
  'comments_count': instance.commentsCount,
  'shares_count': instance.sharesCount,
  'status': instance.status,
  'created_at': instance.createdAt,
  'edited_at': instance.editedAt,
  'updated_at': instance.updatedAt,
  'author': instance.author,
};
