// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'post_dto.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// dart format off
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$PostDto {

@JsonKey(name: 'post_id') String get postId;@JsonKey(name: 'author_id') String get authorId;@JsonKey(name: 'author_context') String get authorContext;@JsonKey(name: 'context_entity_id') String? get contextEntityId;@JsonKey(name: 'post_type') String get postType; String? get text;@JsonKey(name: 'media_urls') List<String> get mediaUrls; List<dynamic> get media;@JsonKey(name: 'linked_match_id') String? get linkedMatchId;@JsonKey(name: 'linked_tournament_id') String? get linkedTournamentId;@JsonKey(name: 'linked_team_id') String? get linkedTeamId;@JsonKey(name: 'linked_player_ids') List<String> get linkedPlayerIds;@JsonKey(name: 'auto_generated') bool get autoGenerated;@JsonKey(name: 'is_pinned') bool get isPinned;@JsonKey(name: 'likes_count') int get likesCount;@JsonKey(name: 'comments_count') int get commentsCount;@JsonKey(name: 'shares_count') int get sharesCount;@JsonKey(name: 'is_liked') bool get isLiked;@JsonKey(name: 'is_bookmarked') bool get isBookmarked; String get status;@JsonKey(name: 'created_at') String get createdAt;@JsonKey(name: 'edited_at') String? get editedAt;@JsonKey(name: 'updated_at') String get updatedAt;// Embedded profiles join (alias `author`).
 Map<String, dynamic>? get author;// Embedded teams join (alias `team`).
 Map<String, dynamic>? get team;
/// Create a copy of PostDto
/// with the given fields replaced by the non-null parameter values.
@JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
$PostDtoCopyWith<PostDto> get copyWith => _$PostDtoCopyWithImpl<PostDto>(this as PostDto, _$identity);

  /// Serializes this PostDto to a JSON map.
  Map<String, dynamic> toJson();


@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is PostDto&&(identical(other.postId, postId) || other.postId == postId)&&(identical(other.authorId, authorId) || other.authorId == authorId)&&(identical(other.authorContext, authorContext) || other.authorContext == authorContext)&&(identical(other.contextEntityId, contextEntityId) || other.contextEntityId == contextEntityId)&&(identical(other.postType, postType) || other.postType == postType)&&(identical(other.text, text) || other.text == text)&&const DeepCollectionEquality().equals(other.mediaUrls, mediaUrls)&&const DeepCollectionEquality().equals(other.media, media)&&(identical(other.linkedMatchId, linkedMatchId) || other.linkedMatchId == linkedMatchId)&&(identical(other.linkedTournamentId, linkedTournamentId) || other.linkedTournamentId == linkedTournamentId)&&(identical(other.linkedTeamId, linkedTeamId) || other.linkedTeamId == linkedTeamId)&&const DeepCollectionEquality().equals(other.linkedPlayerIds, linkedPlayerIds)&&(identical(other.autoGenerated, autoGenerated) || other.autoGenerated == autoGenerated)&&(identical(other.isPinned, isPinned) || other.isPinned == isPinned)&&(identical(other.likesCount, likesCount) || other.likesCount == likesCount)&&(identical(other.commentsCount, commentsCount) || other.commentsCount == commentsCount)&&(identical(other.sharesCount, sharesCount) || other.sharesCount == sharesCount)&&(identical(other.isLiked, isLiked) || other.isLiked == isLiked)&&(identical(other.isBookmarked, isBookmarked) || other.isBookmarked == isBookmarked)&&(identical(other.status, status) || other.status == status)&&(identical(other.createdAt, createdAt) || other.createdAt == createdAt)&&(identical(other.editedAt, editedAt) || other.editedAt == editedAt)&&(identical(other.updatedAt, updatedAt) || other.updatedAt == updatedAt)&&const DeepCollectionEquality().equals(other.author, author)&&const DeepCollectionEquality().equals(other.team, team));
}

@JsonKey(includeFromJson: false, includeToJson: false)
@override
int get hashCode => Object.hashAll([runtimeType,postId,authorId,authorContext,contextEntityId,postType,text,const DeepCollectionEquality().hash(mediaUrls),const DeepCollectionEquality().hash(media),linkedMatchId,linkedTournamentId,linkedTeamId,const DeepCollectionEquality().hash(linkedPlayerIds),autoGenerated,isPinned,likesCount,commentsCount,sharesCount,isLiked,isBookmarked,status,createdAt,editedAt,updatedAt,const DeepCollectionEquality().hash(author),const DeepCollectionEquality().hash(team)]);

@override
String toString() {
  return 'PostDto(postId: $postId, authorId: $authorId, authorContext: $authorContext, contextEntityId: $contextEntityId, postType: $postType, text: $text, mediaUrls: $mediaUrls, media: $media, linkedMatchId: $linkedMatchId, linkedTournamentId: $linkedTournamentId, linkedTeamId: $linkedTeamId, linkedPlayerIds: $linkedPlayerIds, autoGenerated: $autoGenerated, isPinned: $isPinned, likesCount: $likesCount, commentsCount: $commentsCount, sharesCount: $sharesCount, isLiked: $isLiked, isBookmarked: $isBookmarked, status: $status, createdAt: $createdAt, editedAt: $editedAt, updatedAt: $updatedAt, author: $author, team: $team)';
}


}

/// @nodoc
abstract mixin class $PostDtoCopyWith<$Res>  {
  factory $PostDtoCopyWith(PostDto value, $Res Function(PostDto) _then) = _$PostDtoCopyWithImpl;
@useResult
$Res call({
@JsonKey(name: 'post_id') String postId,@JsonKey(name: 'author_id') String authorId,@JsonKey(name: 'author_context') String authorContext,@JsonKey(name: 'context_entity_id') String? contextEntityId,@JsonKey(name: 'post_type') String postType, String? text,@JsonKey(name: 'media_urls') List<String> mediaUrls, List<dynamic> media,@JsonKey(name: 'linked_match_id') String? linkedMatchId,@JsonKey(name: 'linked_tournament_id') String? linkedTournamentId,@JsonKey(name: 'linked_team_id') String? linkedTeamId,@JsonKey(name: 'linked_player_ids') List<String> linkedPlayerIds,@JsonKey(name: 'auto_generated') bool autoGenerated,@JsonKey(name: 'is_pinned') bool isPinned,@JsonKey(name: 'likes_count') int likesCount,@JsonKey(name: 'comments_count') int commentsCount,@JsonKey(name: 'shares_count') int sharesCount,@JsonKey(name: 'is_liked') bool isLiked,@JsonKey(name: 'is_bookmarked') bool isBookmarked, String status,@JsonKey(name: 'created_at') String createdAt,@JsonKey(name: 'edited_at') String? editedAt,@JsonKey(name: 'updated_at') String updatedAt, Map<String, dynamic>? author, Map<String, dynamic>? team
});




}
/// @nodoc
class _$PostDtoCopyWithImpl<$Res>
    implements $PostDtoCopyWith<$Res> {
  _$PostDtoCopyWithImpl(this._self, this._then);

  final PostDto _self;
  final $Res Function(PostDto) _then;

/// Create a copy of PostDto
/// with the given fields replaced by the non-null parameter values.
@pragma('vm:prefer-inline') @override $Res call({Object? postId = null,Object? authorId = null,Object? authorContext = null,Object? contextEntityId = freezed,Object? postType = null,Object? text = freezed,Object? mediaUrls = null,Object? media = null,Object? linkedMatchId = freezed,Object? linkedTournamentId = freezed,Object? linkedTeamId = freezed,Object? linkedPlayerIds = null,Object? autoGenerated = null,Object? isPinned = null,Object? likesCount = null,Object? commentsCount = null,Object? sharesCount = null,Object? isLiked = null,Object? isBookmarked = null,Object? status = null,Object? createdAt = null,Object? editedAt = freezed,Object? updatedAt = null,Object? author = freezed,Object? team = freezed,}) {
  return _then(_self.copyWith(
postId: null == postId ? _self.postId : postId // ignore: cast_nullable_to_non_nullable
as String,authorId: null == authorId ? _self.authorId : authorId // ignore: cast_nullable_to_non_nullable
as String,authorContext: null == authorContext ? _self.authorContext : authorContext // ignore: cast_nullable_to_non_nullable
as String,contextEntityId: freezed == contextEntityId ? _self.contextEntityId : contextEntityId // ignore: cast_nullable_to_non_nullable
as String?,postType: null == postType ? _self.postType : postType // ignore: cast_nullable_to_non_nullable
as String,text: freezed == text ? _self.text : text // ignore: cast_nullable_to_non_nullable
as String?,mediaUrls: null == mediaUrls ? _self.mediaUrls : mediaUrls // ignore: cast_nullable_to_non_nullable
as List<String>,media: null == media ? _self.media : media // ignore: cast_nullable_to_non_nullable
as List<dynamic>,linkedMatchId: freezed == linkedMatchId ? _self.linkedMatchId : linkedMatchId // ignore: cast_nullable_to_non_nullable
as String?,linkedTournamentId: freezed == linkedTournamentId ? _self.linkedTournamentId : linkedTournamentId // ignore: cast_nullable_to_non_nullable
as String?,linkedTeamId: freezed == linkedTeamId ? _self.linkedTeamId : linkedTeamId // ignore: cast_nullable_to_non_nullable
as String?,linkedPlayerIds: null == linkedPlayerIds ? _self.linkedPlayerIds : linkedPlayerIds // ignore: cast_nullable_to_non_nullable
as List<String>,autoGenerated: null == autoGenerated ? _self.autoGenerated : autoGenerated // ignore: cast_nullable_to_non_nullable
as bool,isPinned: null == isPinned ? _self.isPinned : isPinned // ignore: cast_nullable_to_non_nullable
as bool,likesCount: null == likesCount ? _self.likesCount : likesCount // ignore: cast_nullable_to_non_nullable
as int,commentsCount: null == commentsCount ? _self.commentsCount : commentsCount // ignore: cast_nullable_to_non_nullable
as int,sharesCount: null == sharesCount ? _self.sharesCount : sharesCount // ignore: cast_nullable_to_non_nullable
as int,isLiked: null == isLiked ? _self.isLiked : isLiked // ignore: cast_nullable_to_non_nullable
as bool,isBookmarked: null == isBookmarked ? _self.isBookmarked : isBookmarked // ignore: cast_nullable_to_non_nullable
as bool,status: null == status ? _self.status : status // ignore: cast_nullable_to_non_nullable
as String,createdAt: null == createdAt ? _self.createdAt : createdAt // ignore: cast_nullable_to_non_nullable
as String,editedAt: freezed == editedAt ? _self.editedAt : editedAt // ignore: cast_nullable_to_non_nullable
as String?,updatedAt: null == updatedAt ? _self.updatedAt : updatedAt // ignore: cast_nullable_to_non_nullable
as String,author: freezed == author ? _self.author : author // ignore: cast_nullable_to_non_nullable
as Map<String, dynamic>?,team: freezed == team ? _self.team : team // ignore: cast_nullable_to_non_nullable
as Map<String, dynamic>?,
  ));
}

}


/// Adds pattern-matching-related methods to [PostDto].
extension PostDtoPatterns on PostDto {
/// A variant of `map` that fallback to returning `orElse`.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case _:
///     return orElse();
/// }
/// ```

@optionalTypeArgs TResult maybeMap<TResult extends Object?>(TResult Function( _PostDto value)?  $default,{required TResult orElse(),}){
final _that = this;
switch (_that) {
case _PostDto() when $default != null:
return $default(_that);case _:
  return orElse();

}
}
/// A `switch`-like method, using callbacks.
///
/// Callbacks receives the raw object, upcasted.
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case final Subclass2 value:
///     return ...;
/// }
/// ```

@optionalTypeArgs TResult map<TResult extends Object?>(TResult Function( _PostDto value)  $default,){
final _that = this;
switch (_that) {
case _PostDto():
return $default(_that);case _:
  throw StateError('Unexpected subclass');

}
}
/// A variant of `map` that fallback to returning `null`.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case _:
///     return null;
/// }
/// ```

@optionalTypeArgs TResult? mapOrNull<TResult extends Object?>(TResult? Function( _PostDto value)?  $default,){
final _that = this;
switch (_that) {
case _PostDto() when $default != null:
return $default(_that);case _:
  return null;

}
}
/// A variant of `when` that fallback to an `orElse` callback.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case _:
///     return orElse();
/// }
/// ```

@optionalTypeArgs TResult maybeWhen<TResult extends Object?>(TResult Function(@JsonKey(name: 'post_id')  String postId, @JsonKey(name: 'author_id')  String authorId, @JsonKey(name: 'author_context')  String authorContext, @JsonKey(name: 'context_entity_id')  String? contextEntityId, @JsonKey(name: 'post_type')  String postType,  String? text, @JsonKey(name: 'media_urls')  List<String> mediaUrls,  List<dynamic> media, @JsonKey(name: 'linked_match_id')  String? linkedMatchId, @JsonKey(name: 'linked_tournament_id')  String? linkedTournamentId, @JsonKey(name: 'linked_team_id')  String? linkedTeamId, @JsonKey(name: 'linked_player_ids')  List<String> linkedPlayerIds, @JsonKey(name: 'auto_generated')  bool autoGenerated, @JsonKey(name: 'is_pinned')  bool isPinned, @JsonKey(name: 'likes_count')  int likesCount, @JsonKey(name: 'comments_count')  int commentsCount, @JsonKey(name: 'shares_count')  int sharesCount, @JsonKey(name: 'is_liked')  bool isLiked, @JsonKey(name: 'is_bookmarked')  bool isBookmarked,  String status, @JsonKey(name: 'created_at')  String createdAt, @JsonKey(name: 'edited_at')  String? editedAt, @JsonKey(name: 'updated_at')  String updatedAt,  Map<String, dynamic>? author,  Map<String, dynamic>? team)?  $default,{required TResult orElse(),}) {final _that = this;
switch (_that) {
case _PostDto() when $default != null:
return $default(_that.postId,_that.authorId,_that.authorContext,_that.contextEntityId,_that.postType,_that.text,_that.mediaUrls,_that.media,_that.linkedMatchId,_that.linkedTournamentId,_that.linkedTeamId,_that.linkedPlayerIds,_that.autoGenerated,_that.isPinned,_that.likesCount,_that.commentsCount,_that.sharesCount,_that.isLiked,_that.isBookmarked,_that.status,_that.createdAt,_that.editedAt,_that.updatedAt,_that.author,_that.team);case _:
  return orElse();

}
}
/// A `switch`-like method, using callbacks.
///
/// As opposed to `map`, this offers destructuring.
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case Subclass2(:final field2):
///     return ...;
/// }
/// ```

@optionalTypeArgs TResult when<TResult extends Object?>(TResult Function(@JsonKey(name: 'post_id')  String postId, @JsonKey(name: 'author_id')  String authorId, @JsonKey(name: 'author_context')  String authorContext, @JsonKey(name: 'context_entity_id')  String? contextEntityId, @JsonKey(name: 'post_type')  String postType,  String? text, @JsonKey(name: 'media_urls')  List<String> mediaUrls,  List<dynamic> media, @JsonKey(name: 'linked_match_id')  String? linkedMatchId, @JsonKey(name: 'linked_tournament_id')  String? linkedTournamentId, @JsonKey(name: 'linked_team_id')  String? linkedTeamId, @JsonKey(name: 'linked_player_ids')  List<String> linkedPlayerIds, @JsonKey(name: 'auto_generated')  bool autoGenerated, @JsonKey(name: 'is_pinned')  bool isPinned, @JsonKey(name: 'likes_count')  int likesCount, @JsonKey(name: 'comments_count')  int commentsCount, @JsonKey(name: 'shares_count')  int sharesCount, @JsonKey(name: 'is_liked')  bool isLiked, @JsonKey(name: 'is_bookmarked')  bool isBookmarked,  String status, @JsonKey(name: 'created_at')  String createdAt, @JsonKey(name: 'edited_at')  String? editedAt, @JsonKey(name: 'updated_at')  String updatedAt,  Map<String, dynamic>? author,  Map<String, dynamic>? team)  $default,) {final _that = this;
switch (_that) {
case _PostDto():
return $default(_that.postId,_that.authorId,_that.authorContext,_that.contextEntityId,_that.postType,_that.text,_that.mediaUrls,_that.media,_that.linkedMatchId,_that.linkedTournamentId,_that.linkedTeamId,_that.linkedPlayerIds,_that.autoGenerated,_that.isPinned,_that.likesCount,_that.commentsCount,_that.sharesCount,_that.isLiked,_that.isBookmarked,_that.status,_that.createdAt,_that.editedAt,_that.updatedAt,_that.author,_that.team);case _:
  throw StateError('Unexpected subclass');

}
}
/// A variant of `when` that fallback to returning `null`
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case _:
///     return null;
/// }
/// ```

@optionalTypeArgs TResult? whenOrNull<TResult extends Object?>(TResult? Function(@JsonKey(name: 'post_id')  String postId, @JsonKey(name: 'author_id')  String authorId, @JsonKey(name: 'author_context')  String authorContext, @JsonKey(name: 'context_entity_id')  String? contextEntityId, @JsonKey(name: 'post_type')  String postType,  String? text, @JsonKey(name: 'media_urls')  List<String> mediaUrls,  List<dynamic> media, @JsonKey(name: 'linked_match_id')  String? linkedMatchId, @JsonKey(name: 'linked_tournament_id')  String? linkedTournamentId, @JsonKey(name: 'linked_team_id')  String? linkedTeamId, @JsonKey(name: 'linked_player_ids')  List<String> linkedPlayerIds, @JsonKey(name: 'auto_generated')  bool autoGenerated, @JsonKey(name: 'is_pinned')  bool isPinned, @JsonKey(name: 'likes_count')  int likesCount, @JsonKey(name: 'comments_count')  int commentsCount, @JsonKey(name: 'shares_count')  int sharesCount, @JsonKey(name: 'is_liked')  bool isLiked, @JsonKey(name: 'is_bookmarked')  bool isBookmarked,  String status, @JsonKey(name: 'created_at')  String createdAt, @JsonKey(name: 'edited_at')  String? editedAt, @JsonKey(name: 'updated_at')  String updatedAt,  Map<String, dynamic>? author,  Map<String, dynamic>? team)?  $default,) {final _that = this;
switch (_that) {
case _PostDto() when $default != null:
return $default(_that.postId,_that.authorId,_that.authorContext,_that.contextEntityId,_that.postType,_that.text,_that.mediaUrls,_that.media,_that.linkedMatchId,_that.linkedTournamentId,_that.linkedTeamId,_that.linkedPlayerIds,_that.autoGenerated,_that.isPinned,_that.likesCount,_that.commentsCount,_that.sharesCount,_that.isLiked,_that.isBookmarked,_that.status,_that.createdAt,_that.editedAt,_that.updatedAt,_that.author,_that.team);case _:
  return null;

}
}

}

/// @nodoc
@JsonSerializable()

class _PostDto extends PostDto {
  const _PostDto({@JsonKey(name: 'post_id') required this.postId, @JsonKey(name: 'author_id') required this.authorId, @JsonKey(name: 'author_context') this.authorContext = 'personal', @JsonKey(name: 'context_entity_id') this.contextEntityId, @JsonKey(name: 'post_type') required this.postType, this.text, @JsonKey(name: 'media_urls') final  List<String> mediaUrls = const <String>[], final  List<dynamic> media = const <dynamic>[], @JsonKey(name: 'linked_match_id') this.linkedMatchId, @JsonKey(name: 'linked_tournament_id') this.linkedTournamentId, @JsonKey(name: 'linked_team_id') this.linkedTeamId, @JsonKey(name: 'linked_player_ids') final  List<String> linkedPlayerIds = const <String>[], @JsonKey(name: 'auto_generated') this.autoGenerated = false, @JsonKey(name: 'is_pinned') this.isPinned = false, @JsonKey(name: 'likes_count') this.likesCount = 0, @JsonKey(name: 'comments_count') this.commentsCount = 0, @JsonKey(name: 'shares_count') this.sharesCount = 0, @JsonKey(name: 'is_liked') this.isLiked = false, @JsonKey(name: 'is_bookmarked') this.isBookmarked = false, this.status = 'active', @JsonKey(name: 'created_at') required this.createdAt, @JsonKey(name: 'edited_at') this.editedAt, @JsonKey(name: 'updated_at') required this.updatedAt, final  Map<String, dynamic>? author, final  Map<String, dynamic>? team}): _mediaUrls = mediaUrls,_media = media,_linkedPlayerIds = linkedPlayerIds,_author = author,_team = team,super._();
  factory _PostDto.fromJson(Map<String, dynamic> json) => _$PostDtoFromJson(json);

@override@JsonKey(name: 'post_id') final  String postId;
@override@JsonKey(name: 'author_id') final  String authorId;
@override@JsonKey(name: 'author_context') final  String authorContext;
@override@JsonKey(name: 'context_entity_id') final  String? contextEntityId;
@override@JsonKey(name: 'post_type') final  String postType;
@override final  String? text;
 final  List<String> _mediaUrls;
@override@JsonKey(name: 'media_urls') List<String> get mediaUrls {
  if (_mediaUrls is EqualUnmodifiableListView) return _mediaUrls;
  // ignore: implicit_dynamic_type
  return EqualUnmodifiableListView(_mediaUrls);
}

 final  List<dynamic> _media;
@override@JsonKey() List<dynamic> get media {
  if (_media is EqualUnmodifiableListView) return _media;
  // ignore: implicit_dynamic_type
  return EqualUnmodifiableListView(_media);
}

@override@JsonKey(name: 'linked_match_id') final  String? linkedMatchId;
@override@JsonKey(name: 'linked_tournament_id') final  String? linkedTournamentId;
@override@JsonKey(name: 'linked_team_id') final  String? linkedTeamId;
 final  List<String> _linkedPlayerIds;
@override@JsonKey(name: 'linked_player_ids') List<String> get linkedPlayerIds {
  if (_linkedPlayerIds is EqualUnmodifiableListView) return _linkedPlayerIds;
  // ignore: implicit_dynamic_type
  return EqualUnmodifiableListView(_linkedPlayerIds);
}

@override@JsonKey(name: 'auto_generated') final  bool autoGenerated;
@override@JsonKey(name: 'is_pinned') final  bool isPinned;
@override@JsonKey(name: 'likes_count') final  int likesCount;
@override@JsonKey(name: 'comments_count') final  int commentsCount;
@override@JsonKey(name: 'shares_count') final  int sharesCount;
@override@JsonKey(name: 'is_liked') final  bool isLiked;
@override@JsonKey(name: 'is_bookmarked') final  bool isBookmarked;
@override@JsonKey() final  String status;
@override@JsonKey(name: 'created_at') final  String createdAt;
@override@JsonKey(name: 'edited_at') final  String? editedAt;
@override@JsonKey(name: 'updated_at') final  String updatedAt;
// Embedded profiles join (alias `author`).
 final  Map<String, dynamic>? _author;
// Embedded profiles join (alias `author`).
@override Map<String, dynamic>? get author {
  final value = _author;
  if (value == null) return null;
  if (_author is EqualUnmodifiableMapView) return _author;
  // ignore: implicit_dynamic_type
  return EqualUnmodifiableMapView(value);
}

// Embedded teams join (alias `team`).
 final  Map<String, dynamic>? _team;
// Embedded teams join (alias `team`).
@override Map<String, dynamic>? get team {
  final value = _team;
  if (value == null) return null;
  if (_team is EqualUnmodifiableMapView) return _team;
  // ignore: implicit_dynamic_type
  return EqualUnmodifiableMapView(value);
}


/// Create a copy of PostDto
/// with the given fields replaced by the non-null parameter values.
@override @JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
_$PostDtoCopyWith<_PostDto> get copyWith => __$PostDtoCopyWithImpl<_PostDto>(this, _$identity);

@override
Map<String, dynamic> toJson() {
  return _$PostDtoToJson(this, );
}

@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is _PostDto&&(identical(other.postId, postId) || other.postId == postId)&&(identical(other.authorId, authorId) || other.authorId == authorId)&&(identical(other.authorContext, authorContext) || other.authorContext == authorContext)&&(identical(other.contextEntityId, contextEntityId) || other.contextEntityId == contextEntityId)&&(identical(other.postType, postType) || other.postType == postType)&&(identical(other.text, text) || other.text == text)&&const DeepCollectionEquality().equals(other._mediaUrls, _mediaUrls)&&const DeepCollectionEquality().equals(other._media, _media)&&(identical(other.linkedMatchId, linkedMatchId) || other.linkedMatchId == linkedMatchId)&&(identical(other.linkedTournamentId, linkedTournamentId) || other.linkedTournamentId == linkedTournamentId)&&(identical(other.linkedTeamId, linkedTeamId) || other.linkedTeamId == linkedTeamId)&&const DeepCollectionEquality().equals(other._linkedPlayerIds, _linkedPlayerIds)&&(identical(other.autoGenerated, autoGenerated) || other.autoGenerated == autoGenerated)&&(identical(other.isPinned, isPinned) || other.isPinned == isPinned)&&(identical(other.likesCount, likesCount) || other.likesCount == likesCount)&&(identical(other.commentsCount, commentsCount) || other.commentsCount == commentsCount)&&(identical(other.sharesCount, sharesCount) || other.sharesCount == sharesCount)&&(identical(other.isLiked, isLiked) || other.isLiked == isLiked)&&(identical(other.isBookmarked, isBookmarked) || other.isBookmarked == isBookmarked)&&(identical(other.status, status) || other.status == status)&&(identical(other.createdAt, createdAt) || other.createdAt == createdAt)&&(identical(other.editedAt, editedAt) || other.editedAt == editedAt)&&(identical(other.updatedAt, updatedAt) || other.updatedAt == updatedAt)&&const DeepCollectionEquality().equals(other._author, _author)&&const DeepCollectionEquality().equals(other._team, _team));
}

@JsonKey(includeFromJson: false, includeToJson: false)
@override
int get hashCode => Object.hashAll([runtimeType,postId,authorId,authorContext,contextEntityId,postType,text,const DeepCollectionEquality().hash(_mediaUrls),const DeepCollectionEquality().hash(_media),linkedMatchId,linkedTournamentId,linkedTeamId,const DeepCollectionEquality().hash(_linkedPlayerIds),autoGenerated,isPinned,likesCount,commentsCount,sharesCount,isLiked,isBookmarked,status,createdAt,editedAt,updatedAt,const DeepCollectionEquality().hash(_author),const DeepCollectionEquality().hash(_team)]);

@override
String toString() {
  return 'PostDto(postId: $postId, authorId: $authorId, authorContext: $authorContext, contextEntityId: $contextEntityId, postType: $postType, text: $text, mediaUrls: $mediaUrls, media: $media, linkedMatchId: $linkedMatchId, linkedTournamentId: $linkedTournamentId, linkedTeamId: $linkedTeamId, linkedPlayerIds: $linkedPlayerIds, autoGenerated: $autoGenerated, isPinned: $isPinned, likesCount: $likesCount, commentsCount: $commentsCount, sharesCount: $sharesCount, isLiked: $isLiked, isBookmarked: $isBookmarked, status: $status, createdAt: $createdAt, editedAt: $editedAt, updatedAt: $updatedAt, author: $author, team: $team)';
}


}

/// @nodoc
abstract mixin class _$PostDtoCopyWith<$Res> implements $PostDtoCopyWith<$Res> {
  factory _$PostDtoCopyWith(_PostDto value, $Res Function(_PostDto) _then) = __$PostDtoCopyWithImpl;
@override @useResult
$Res call({
@JsonKey(name: 'post_id') String postId,@JsonKey(name: 'author_id') String authorId,@JsonKey(name: 'author_context') String authorContext,@JsonKey(name: 'context_entity_id') String? contextEntityId,@JsonKey(name: 'post_type') String postType, String? text,@JsonKey(name: 'media_urls') List<String> mediaUrls, List<dynamic> media,@JsonKey(name: 'linked_match_id') String? linkedMatchId,@JsonKey(name: 'linked_tournament_id') String? linkedTournamentId,@JsonKey(name: 'linked_team_id') String? linkedTeamId,@JsonKey(name: 'linked_player_ids') List<String> linkedPlayerIds,@JsonKey(name: 'auto_generated') bool autoGenerated,@JsonKey(name: 'is_pinned') bool isPinned,@JsonKey(name: 'likes_count') int likesCount,@JsonKey(name: 'comments_count') int commentsCount,@JsonKey(name: 'shares_count') int sharesCount,@JsonKey(name: 'is_liked') bool isLiked,@JsonKey(name: 'is_bookmarked') bool isBookmarked, String status,@JsonKey(name: 'created_at') String createdAt,@JsonKey(name: 'edited_at') String? editedAt,@JsonKey(name: 'updated_at') String updatedAt, Map<String, dynamic>? author, Map<String, dynamic>? team
});




}
/// @nodoc
class __$PostDtoCopyWithImpl<$Res>
    implements _$PostDtoCopyWith<$Res> {
  __$PostDtoCopyWithImpl(this._self, this._then);

  final _PostDto _self;
  final $Res Function(_PostDto) _then;

/// Create a copy of PostDto
/// with the given fields replaced by the non-null parameter values.
@override @pragma('vm:prefer-inline') $Res call({Object? postId = null,Object? authorId = null,Object? authorContext = null,Object? contextEntityId = freezed,Object? postType = null,Object? text = freezed,Object? mediaUrls = null,Object? media = null,Object? linkedMatchId = freezed,Object? linkedTournamentId = freezed,Object? linkedTeamId = freezed,Object? linkedPlayerIds = null,Object? autoGenerated = null,Object? isPinned = null,Object? likesCount = null,Object? commentsCount = null,Object? sharesCount = null,Object? isLiked = null,Object? isBookmarked = null,Object? status = null,Object? createdAt = null,Object? editedAt = freezed,Object? updatedAt = null,Object? author = freezed,Object? team = freezed,}) {
  return _then(_PostDto(
postId: null == postId ? _self.postId : postId // ignore: cast_nullable_to_non_nullable
as String,authorId: null == authorId ? _self.authorId : authorId // ignore: cast_nullable_to_non_nullable
as String,authorContext: null == authorContext ? _self.authorContext : authorContext // ignore: cast_nullable_to_non_nullable
as String,contextEntityId: freezed == contextEntityId ? _self.contextEntityId : contextEntityId // ignore: cast_nullable_to_non_nullable
as String?,postType: null == postType ? _self.postType : postType // ignore: cast_nullable_to_non_nullable
as String,text: freezed == text ? _self.text : text // ignore: cast_nullable_to_non_nullable
as String?,mediaUrls: null == mediaUrls ? _self._mediaUrls : mediaUrls // ignore: cast_nullable_to_non_nullable
as List<String>,media: null == media ? _self._media : media // ignore: cast_nullable_to_non_nullable
as List<dynamic>,linkedMatchId: freezed == linkedMatchId ? _self.linkedMatchId : linkedMatchId // ignore: cast_nullable_to_non_nullable
as String?,linkedTournamentId: freezed == linkedTournamentId ? _self.linkedTournamentId : linkedTournamentId // ignore: cast_nullable_to_non_nullable
as String?,linkedTeamId: freezed == linkedTeamId ? _self.linkedTeamId : linkedTeamId // ignore: cast_nullable_to_non_nullable
as String?,linkedPlayerIds: null == linkedPlayerIds ? _self._linkedPlayerIds : linkedPlayerIds // ignore: cast_nullable_to_non_nullable
as List<String>,autoGenerated: null == autoGenerated ? _self.autoGenerated : autoGenerated // ignore: cast_nullable_to_non_nullable
as bool,isPinned: null == isPinned ? _self.isPinned : isPinned // ignore: cast_nullable_to_non_nullable
as bool,likesCount: null == likesCount ? _self.likesCount : likesCount // ignore: cast_nullable_to_non_nullable
as int,commentsCount: null == commentsCount ? _self.commentsCount : commentsCount // ignore: cast_nullable_to_non_nullable
as int,sharesCount: null == sharesCount ? _self.sharesCount : sharesCount // ignore: cast_nullable_to_non_nullable
as int,isLiked: null == isLiked ? _self.isLiked : isLiked // ignore: cast_nullable_to_non_nullable
as bool,isBookmarked: null == isBookmarked ? _self.isBookmarked : isBookmarked // ignore: cast_nullable_to_non_nullable
as bool,status: null == status ? _self.status : status // ignore: cast_nullable_to_non_nullable
as String,createdAt: null == createdAt ? _self.createdAt : createdAt // ignore: cast_nullable_to_non_nullable
as String,editedAt: freezed == editedAt ? _self.editedAt : editedAt // ignore: cast_nullable_to_non_nullable
as String?,updatedAt: null == updatedAt ? _self.updatedAt : updatedAt // ignore: cast_nullable_to_non_nullable
as String,author: freezed == author ? _self._author : author // ignore: cast_nullable_to_non_nullable
as Map<String, dynamic>?,team: freezed == team ? _self._team : team // ignore: cast_nullable_to_non_nullable
as Map<String, dynamic>?,
  ));
}


}

// dart format on
