import 'package:freezed_annotation/freezed_annotation.dart';

import '../../domain/entities/post.dart';
import '../../domain/entities/post_media.dart';

part 'post_dto.freezed.dart';
part 'post_dto.g.dart';

/// Wire-format `posts` row (migration 0510 + 0511). `media` is the rich jsonb
/// array of `{url, blurhash, width, height}`; `author` is the embedded
/// `profiles` join (display_name / username / profile_photo_url).
@freezed
abstract class PostDto with _$PostDto {
  const factory PostDto({
    @JsonKey(name: 'post_id') required String postId,
    @JsonKey(name: 'author_id') required String authorId,
    @JsonKey(name: 'author_context') @Default('personal') String authorContext,
    @JsonKey(name: 'context_entity_id') String? contextEntityId,
    @JsonKey(name: 'post_type') required String postType,
    String? text,
    @JsonKey(name: 'media_urls') @Default(<String>[]) List<String> mediaUrls,
    @Default(<dynamic>[]) List<dynamic> media,
    @JsonKey(name: 'linked_match_id') String? linkedMatchId,
    @JsonKey(name: 'linked_tournament_id') String? linkedTournamentId,
    @JsonKey(name: 'linked_team_id') String? linkedTeamId,
    @JsonKey(name: 'linked_player_ids')
    @Default(<String>[]) List<String> linkedPlayerIds,
    @JsonKey(name: 'auto_generated') @Default(false) bool autoGenerated,
    @JsonKey(name: 'is_pinned') @Default(false) bool isPinned,
    @JsonKey(name: 'likes_count') @Default(0) int likesCount,
    @JsonKey(name: 'comments_count') @Default(0) int commentsCount,
    @JsonKey(name: 'shares_count') @Default(0) int sharesCount,
    @JsonKey(name: 'is_liked') @Default(false) bool isLiked,
    @JsonKey(name: 'is_bookmarked') @Default(false) bool isBookmarked,
    @Default('active') String status,
    @JsonKey(name: 'created_at') required String createdAt,
    @JsonKey(name: 'edited_at') String? editedAt,
    @JsonKey(name: 'updated_at') required String updatedAt,
    // Embedded profiles join (alias `author`).
    Map<String, dynamic>? author,
  }) = _PostDto;

  const PostDto._();

  factory PostDto.fromJson(Map<String, dynamic> json) =>
      _$PostDtoFromJson(json);

  Post toEntity({bool? isLikedOverride, bool? isBookmarkedOverride}) => Post(
        id: PostId(postId),
        authorId: authorId,
        authorContext: PostAuthorContext.fromWire(authorContext),
        contextEntityId: contextEntityId,
        type: PostType.fromWire(postType),
        text: text,
        media: _parseMedia(),
        linkedMatchId: linkedMatchId,
        linkedTournamentId: linkedTournamentId,
        linkedTeamId: linkedTeamId,
        linkedPlayerIds: linkedPlayerIds,
        autoGenerated: autoGenerated,
        isPinned: isPinned,
        likesCount: likesCount,
        commentsCount: commentsCount,
        sharesCount: sharesCount,
        isLiked: isLikedOverride ?? isLiked,
        isBookmarked: isBookmarkedOverride ?? isBookmarked,
        status: PostStatus.fromWire(status),
        createdAt: DateTime.parse(createdAt),
        editedAt: editedAt == null ? null : DateTime.tryParse(editedAt!),
        updatedAt: DateTime.parse(updatedAt),
        authorName: author?['display_name'] as String?,
        authorUsername: author?['username'] as String?,
        authorPhotoUrl: author?['profile_photo_url'] as String?,
      );

  /// Prefer the rich `media` jsonb; fall back to bare `media_urls` for any
  /// legacy rows written before the 0511 metadata column existed.
  List<PostMedia> _parseMedia() {
    if (media.isNotEmpty) {
      return media
          .whereType<Map<String, dynamic>>()
          .map((m) => PostMedia(
                url: m['url'] as String? ?? '',
                blurhash: m['blurhash'] as String? ?? '',
                width: (m['width'] as num?)?.toInt() ?? 0,
                height: (m['height'] as num?)?.toInt() ?? 0,
              ))
          .where((x) => x.url.isNotEmpty)
          .toList();
    }
    return mediaUrls
        .map((u) => PostMedia(url: u, blurhash: '', width: 0, height: 0))
        .toList();
  }
}
