// Post UI for the feed/profile — renders a real [Post] (author header + text +
// 1–4 photo mosaic via CkFeedImage + action bar). Lives in the posts feature
// (it's coupled to the Post entity), not in the feature-agnostic core kit.
import 'package:flutter/material.dart';
import 'package:timeago/timeago.dart' as timeago;

import '../../../../core/theme/circk_theme.dart';
import '../../../../core/widgets/v2/ck_feed_image.dart';
import '../../../../core/widgets/v2/v2_kit.dart';
import '../../domain/entities/post.dart';
import '../../domain/entities/post_media.dart';

class FeedPostCard extends StatelessWidget {
  const FeedPostCard({
    super.key,
    required this.post,
    required this.onComment,
    required this.onOpenPhoto,
    this.onAuthorTap,
    this.showAuthor = true,
  });

  final Post post;
  final VoidCallback onComment;
  final void Function(int index) onOpenPhoto;
  final VoidCallback? onAuthorTap;

  /// Hide the author avatar/name on a profile (where every post is the owner's).
  final bool showAuthor;

  @override
  Widget build(BuildContext context) {
    final content = Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _header(),
        if ((post.text ?? '').isNotEmpty) ...[
          const SizedBox(height: 6),
          Text(
            post.text!,
            style: CkType.body(fontSize: 14, height: 1.45, color: CkColors.ink),
          ),
        ],
        if (post.hasMedia) ...[
          const SizedBox(height: 10),
          PostMediaGrid(media: post.media, onOpen: onOpenPhoto),
        ],
        PostActions(
          likes: post.likesCount,
          comments: post.commentsCount,
          onComment: onComment,
        ),
      ],
    );

    return GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTap: onComment,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 14),
        decoration: const BoxDecoration(
          color: CkColors.paper,
          border: Border(top: BorderSide(color: CkColors.hairline)),
        ),
        child: showAuthor
            ? Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  GestureDetector(
                    behavior: HitTestBehavior.opaque,
                    onTap: onAuthorTap,
                    child:
                        Avatar(mono: post.authorMonogram, tone: AvatarTone.ink),
                  ),
                  const SizedBox(width: 12),
                  Expanded(child: content),
                ],
              )
            : content,
      ),
    );
  }

  Widget _header() {
    final time = timeago.format(post.createdAt, locale: 'en_short');
    return Row(
      crossAxisAlignment: CrossAxisAlignment.baseline,
      textBaseline: TextBaseline.alphabetic,
      children: [
        if (showAuthor) ...[
          Flexible(
            child: Text(
              post.authorName ?? 'matchday player',
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: CkType.display(fontSize: 13.5, letterSpacing: -0.01),
            ),
          ),
          if (post.authorUsername != null) ...[
            const SizedBox(width: 6),
            Text('@${post.authorUsername}',
                style: CkType.body(fontSize: 11, color: CkColors.muted)),
          ],
        ],
        if (post.autoGenerated) ...[
          if (showAuthor) const SizedBox(width: 6),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 5, vertical: 2),
            decoration: BoxDecoration(
              color: CkColors.cream,
              borderRadius: BorderRadius.circular(3),
            ),
            child: Text('★ AUTO',
                style: CkType.mono(
                    fontSize: 8.5,
                    fontWeight: FontWeight.w700,
                    letterSpacing: 0.08,
                    color: CkColors.amber)),
          ),
        ],
        const Spacer(),
        Text(time, style: CkType.mono(fontSize: 9, letterSpacing: 0.10)),
      ],
    );
  }
}

/// 1–4 photo mosaic. Single image respects its (clamped) aspect ratio; 2–4 use
/// a fixed-height grid with cover crop. Tapping a cell calls [onOpen].
class PostMediaGrid extends StatelessWidget {
  const PostMediaGrid({super.key, required this.media, required this.onOpen});
  final List<PostMedia> media;
  final void Function(int index) onOpen;

  static const _gap = 2.0;
  static const _gridHeight = 240.0;

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(12),
      child: switch (media.length) {
        0 => const SizedBox.shrink(),
        1 => _single(),
        2 => SizedBox(
            height: _gridHeight,
            child: Row(children: [
              Expanded(child: _cell(0)),
              const SizedBox(width: _gap),
              Expanded(child: _cell(1)),
            ]),
          ),
        3 => SizedBox(
            height: _gridHeight,
            child: Row(children: [
              Expanded(flex: 2, child: _cell(0)),
              const SizedBox(width: _gap),
              Expanded(
                child: Column(children: [
                  Expanded(child: _cell(1)),
                  const SizedBox(height: _gap),
                  Expanded(child: _cell(2)),
                ]),
              ),
            ]),
          ),
        _ => SizedBox(
            height: _gridHeight,
            child: Row(children: [
              Expanded(
                child: Column(children: [
                  Expanded(child: _cell(0)),
                  const SizedBox(height: _gap),
                  Expanded(child: _cell(2)),
                ]),
              ),
              const SizedBox(width: _gap),
              Expanded(
                child: Column(children: [
                  Expanded(child: _cell(1)),
                  const SizedBox(height: _gap),
                  Expanded(child: _cell(3)),
                ]),
              ),
            ]),
          ),
      },
    );
  }

  Widget _single() {
    final m = media[0];
    return GestureDetector(
      onTap: () => onOpen(0),
      child: AspectRatio(
        aspectRatio: m.aspectRatio.clamp(0.8, 1.91),
        child: CkFeedImage(url: m.url, blurhash: m.blurhash, useAspectRatio: false),
      ),
    );
  }

  Widget _cell(int i) {
    final m = media[i];
    return GestureDetector(
      onTap: () => onOpen(i),
      child: CkFeedImage(url: m.url, blurhash: m.blurhash, useAspectRatio: false),
    );
  }
}
